project_id = "jcegxnlzocfypgxaipwq"

[auth.email]
[auth.email.invite]
subject = "Você foi convidado(a) para a InnovaSys"
content_path = "./supabase/templates/invite.html"

[auth.email.recovery]
subject = "Redefinição de senha - InnovaSys"
content_path = "./supabase/templates/recovery.html"

[auth.email.confirmation]
subject = "Confirme seu e-mail - InnovaSys"
content_path = "./supabase/templates/confirmation.html"

[auth.email.magic_link]
subject = "Seu link de acesso - InnovaSys"
content_path = "./supabase/templates/magic_link.html"
